export enum TabName {
  FindGroups = 'Find Groups',
  NewsFeed = 'NewsFeed',
  Activities = 'Activities',
  Explore = 'Explore',
  Timeline = 'Timeline',
  Gallery = 'Gallery',
  Communities = 'Communities',
  Accounts = 'Accounts',
  Members = 'Members',
  Moderators = 'Moderators',
  MyCommunities = 'My Communities',
  Videos = 'Videos',
  Photos = 'Photos',
  Users = 'Users',
}
