export enum TabName {
  NewsFeed = 'NewsFeed',
  Leaderboard = 'Leaderboard',
  Explore = 'Explore',
  Timeline = 'Timeline',
  Activity = 'Activity',
  Gallery = 'Gallery',
  Communities = 'Communities',
  Accounts = 'Accounts',
  Members = 'Members',
  Moderators = 'Moderators',
  MyCommunities = 'MyCommunities',
  Videos = 'Videos',
  Photos = 'Photos',
}
